/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 05:02:16 GMT 2025
 */

package org.apache.commons.lang3.function;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.function.FailableLongPredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FailableLongPredicate_ESTest extends FailableLongPredicate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FailableLongPredicate<Throwable> failableLongPredicate0 = FailableLongPredicate.falsePredicate();
      FailableLongPredicate<Throwable> failableLongPredicate1 = failableLongPredicate0.or(failableLongPredicate0);
      assertFalse(failableLongPredicate1.equals((Object)failableLongPredicate0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FailableLongPredicate<Throwable> failableLongPredicate0 = FailableLongPredicate.truePredicate();
      FailableLongPredicate<Throwable> failableLongPredicate1 = FailableLongPredicate.falsePredicate();
      FailableLongPredicate<Throwable> failableLongPredicate2 = failableLongPredicate0.and(failableLongPredicate1);
      assertFalse(failableLongPredicate2.equals((Object)failableLongPredicate0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FailableLongPredicate<Throwable> failableLongPredicate0 = FailableLongPredicate.truePredicate();
      // Undeclared exception!
      try { 
        failableLongPredicate0.and((FailableLongPredicate<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FailableLongPredicate<Throwable> failableLongPredicate0 = FailableLongPredicate.truePredicate();
      FailableLongPredicate<Throwable> failableLongPredicate1 = failableLongPredicate0.and(failableLongPredicate0);
      FailableLongPredicate<Throwable> failableLongPredicate2 = failableLongPredicate1.or(failableLongPredicate0);
      assertFalse(failableLongPredicate2.equals((Object)failableLongPredicate1));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FailableLongPredicate<Throwable> failableLongPredicate0 = FailableLongPredicate.falsePredicate();
      // Undeclared exception!
      try { 
        failableLongPredicate0.or((FailableLongPredicate<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FailableLongPredicate<Throwable> failableLongPredicate0 = FailableLongPredicate.truePredicate();
      FailableLongPredicate<Throwable> failableLongPredicate1 = failableLongPredicate0.negate();
      assertFalse(failableLongPredicate1.equals((Object)failableLongPredicate0));
  }
}
