/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 04:58:07 GMT 2025
 */

package org.apache.commons.lang3.function;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.function.FailableDoublePredicate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FailableDoublePredicate_ESTest extends FailableDoublePredicate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FailableDoublePredicate<Throwable> failableDoublePredicate0 = FailableDoublePredicate.truePredicate();
      FailableDoublePredicate<Throwable> failableDoublePredicate1 = failableDoublePredicate0.negate();
      FailableDoublePredicate<Throwable> failableDoublePredicate2 = failableDoublePredicate0.or(failableDoublePredicate1);
      assertFalse(failableDoublePredicate2.equals((Object)failableDoublePredicate0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FailableDoublePredicate<Throwable> failableDoublePredicate0 = FailableDoublePredicate.falsePredicate();
      // Undeclared exception!
      try { 
        failableDoublePredicate0.or((FailableDoublePredicate<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FailableDoublePredicate<Throwable> failableDoublePredicate0 = FailableDoublePredicate.falsePredicate();
      // Undeclared exception!
      try { 
        failableDoublePredicate0.and((FailableDoublePredicate<Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FailableDoublePredicate<Throwable> failableDoublePredicate0 = FailableDoublePredicate.truePredicate();
      FailableDoublePredicate<Throwable> failableDoublePredicate1 = failableDoublePredicate0.negate();
      FailableDoublePredicate<Throwable> failableDoublePredicate2 = failableDoublePredicate0.and(failableDoublePredicate1);
      assertFalse(failableDoublePredicate2.equals((Object)failableDoublePredicate1));
  }
}
