/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 01:59:15 GMT 2025
 */

package org.apache.commons.lang3.function;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.function.FailableFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class FailableFunction_ESTest extends FailableFunction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FailableFunction<Throwable, Throwable, Throwable> failableFunction0 = FailableFunction.identity();
      FailableFunction<Throwable, Throwable, Throwable> failableFunction1 = FailableFunction.nop();
      FailableFunction<Throwable, Throwable, Throwable> failableFunction2 = failableFunction0.compose((FailableFunction<? super Throwable, ? extends Throwable, Throwable>) failableFunction1);
      assertFalse(failableFunction2.equals((Object)failableFunction0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FailableFunction<Throwable, Throwable, Throwable> failableFunction0 = FailableFunction.identity();
      FailableFunction<Throwable, Throwable, Throwable> failableFunction1 = FailableFunction.nop();
      FailableFunction<Throwable, Throwable, Throwable> failableFunction2 = failableFunction0.andThen((FailableFunction<? super Throwable, ? extends Throwable, Throwable>) failableFunction1);
      assertFalse(failableFunction2.equals((Object)failableFunction1));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FailableFunction<Throwable, Throwable, Throwable> failableFunction0 = FailableFunction.identity();
      // Undeclared exception!
      try { 
        failableFunction0.compose((FailableFunction<? super Throwable, ? extends Throwable, Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FailableFunction<Throwable, Throwable, Throwable> failableFunction0 = FailableFunction.identity();
      FailableFunction<Throwable, Throwable, Throwable> failableFunction1 = failableFunction0.compose((FailableFunction<? super Throwable, ? extends Throwable, Throwable>) failableFunction0);
      assertFalse(failableFunction1.equals((Object)failableFunction0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FailableFunction<Throwable, Throwable, Throwable> failableFunction0 = FailableFunction.nop();
      // Undeclared exception!
      try { 
        failableFunction0.andThen((FailableFunction<? super Throwable, ? extends Throwable, Throwable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FailableFunction<Throwable, Throwable, Throwable> failableFunction0 = FailableFunction.identity();
      FailableFunction<Throwable, Throwable, Throwable> failableFunction1 = failableFunction0.andThen((FailableFunction<? super Throwable, ? extends Throwable, Throwable>) failableFunction0);
      assertFalse(failableFunction1.equals((Object)failableFunction0));
  }
}
