/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 13:41:43 GMT 2025
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.lang.reflect.Array;
import java.lang.reflect.UndeclaredThrowableException;
import java.nio.CharBuffer;
import java.util.Collection;
import java.util.LinkedList;
import java.util.concurrent.Callable;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import java.util.stream.Stream;
import org.apache.commons.lang3.Functions;
import org.apache.commons.lang3.Streams;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockIOException;
import org.evosuite.runtime.mock.java.lang.MockError;
import org.evosuite.runtime.mock.java.lang.MockRuntimeException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Functions_ESTest extends Functions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("");
      Functions.FailableBiPredicate<IOException, IntStream, IOException> functions_FailableBiPredicate0 = (Functions.FailableBiPredicate<IOException, IntStream, IOException>) mock(Functions.FailableBiPredicate.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(functions_FailableBiPredicate0).test(any(java.io.IOException.class) , any(java.util.stream.IntStream.class));
      boolean boolean0 = Functions.test(functions_FailableBiPredicate0, (IOException) mockIOException0, (IntStream) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Functions.FailablePredicate<IOException, IOException> functions_FailablePredicate0 = (Functions.FailablePredicate<IOException, IOException>) mock(Functions.FailablePredicate.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(functions_FailablePredicate0).test(any(java.io.IOException.class));
      MockError mockError0 = new MockError("temp.dir");
      MockIOException mockIOException0 = new MockIOException(mockError0);
      boolean boolean0 = Functions.test(functions_FailablePredicate0, (IOException) mockIOException0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Functions.FailableBiPredicate<IOException, IOException, IOException> functions_FailableBiPredicate0 = (Functions.FailableBiPredicate<IOException, IOException, IOException>) mock(Functions.FailableBiPredicate.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(functions_FailableBiPredicate0).test(any(java.io.IOException.class) , any(java.io.IOException.class));
      MockIOException mockIOException0 = new MockIOException("/Qyld?8T?)9'$-([");
      boolean boolean0 = Functions.test(functions_FailableBiPredicate0, (IOException) mockIOException0, (IOException) mockIOException0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Functions.FailableSupplier<IOException, IOException> functions_FailableSupplier0 = (Functions.FailableSupplier<IOException, IOException>) mock(Functions.FailableSupplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableSupplier0).get();
      IOException iOException0 = Functions.get(functions_FailableSupplier0);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("");
      Functions.FailableSupplier<IOException, IOException> functions_FailableSupplier0 = (Functions.FailableSupplier<IOException, IOException>) mock(Functions.FailableSupplier.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableSupplier0).get();
      IOException iOException0 = Functions.get(functions_FailableSupplier0);
      assertSame(mockIOException0, iOException0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stream<IntStream> stream0 = Stream.of((IntStream) null);
      UnaryOperator<IntStream> unaryOperator0 = UnaryOperator.identity();
      IntStream intStream0 = stream0.flatMapToInt(unaryOperator0);
      Functions.FailableCallable<IntStream, IOException> functions_FailableCallable0 = (Functions.FailableCallable<IntStream, IOException>) mock(Functions.FailableCallable.class, new ViolatedAssumptionAnswer());
      doReturn(intStream0).when(functions_FailableCallable0).call();
      IntStream intStream1 = Functions.call(functions_FailableCallable0);
      assertSame(intStream1, intStream0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Functions.FailableFunction<IOException, IOException, IOException> functions_FailableFunction0 = (Functions.FailableFunction<IOException, IOException, IOException>) mock(Functions.FailableFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableFunction0).apply(any(java.io.IOException.class));
      MockIOException mockIOException0 = new MockIOException();
      IOException iOException0 = Functions.apply(functions_FailableFunction0, (IOException) mockIOException0);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("");
      Functions.FailableBiFunction<IOException, IOException, IOException, IOException> functions_FailableBiFunction0 = (Functions.FailableBiFunction<IOException, IOException, IOException, IOException>) mock(Functions.FailableBiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableBiFunction0).apply(any(java.io.IOException.class) , any(java.io.IOException.class));
      IOException iOException0 = Functions.apply(functions_FailableBiFunction0, (IOException) mockIOException0, (IOException) null);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      // Undeclared exception!
      try { 
        Functions.test((Functions.FailablePredicate<IOException, IOException>) null, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.stream((Collection<IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.run((Functions.FailableRunnable<IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.rethrow((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // throwable
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.call((Functions.FailableCallable<IOException, IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("This stream is already terminated.");
      // Undeclared exception!
      try { 
        Functions.apply((Functions.FailableFunction<IOException, IOException, IOException>) null, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "'");
      IntStream intStream0 = charBuffer0.codePoints();
      // Undeclared exception!
      try { 
        Functions.apply((Functions.FailableBiFunction<IntStream, IntStream, Object, IOException>) null, intStream0, intStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.accept((Functions.FailableConsumer<IOException, IOException>) null, (IOException) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("");
      // Undeclared exception!
      try { 
        Functions.accept((Functions.FailableBiConsumer<Stream<IntStream>, IOException, IOException>) null, (Stream<IntStream>) null, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableConsumer<Throwable, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<Throwable, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.tryWithResources(functions_FailableRunnable0, functions_FailableConsumer0, (Functions.FailableRunnable<? extends Throwable>[]) null);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableConsumer<Throwable, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<Throwable, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      functions_FailableRunnableArray0[0] = functions_FailableRunnable0;
      Functions.tryWithResources((Functions.FailableRunnable<? extends Throwable>) null, functions_FailableConsumer0, functions_FailableRunnableArray0);
      assertEquals(1, functions_FailableRunnableArray0.length);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.tryWithResources((Functions.FailableRunnable<? extends Throwable>) null, (Functions.FailableConsumer<Throwable, ? extends Throwable>) null, (Functions.FailableRunnable<? extends Throwable>[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.get((Functions.FailableSupplier<Stream<IntStream>, IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.run(functions_FailableRunnable0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockThrowable0);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockIOException0);
        fail("Expecting exception: UncheckedIOException");
      
      } catch(UncheckedIOException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray1 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 0);
      // Undeclared exception!
      try { 
        Functions.tryWithResources(functions_FailableRunnableArray0[0], functions_FailableRunnableArray1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      functions_FailableRunnableArray0[0] = functions_FailableRunnable0;
      Functions.tryWithResources(functions_FailableRunnable0, functions_FailableRunnableArray0);
      assertEquals(1, functions_FailableRunnableArray0.length);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Functions.FailableConsumer<Throwable, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<Throwable, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      // Undeclared exception!
      try { 
        Functions.tryWithResources((Functions.FailableRunnable<? extends Throwable>) null, functions_FailableConsumer0, functions_FailableRunnableArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // runnable
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Functions.FailablePredicate<IOException, IOException> functions_FailablePredicate0 = (Functions.FailablePredicate<IOException, IOException>) mock(Functions.FailablePredicate.class, new ViolatedAssumptionAnswer());
      Predicate<IOException> predicate0 = Functions.asPredicate((Functions.FailablePredicate<IOException, ?>) functions_FailablePredicate0);
      assertNotNull(predicate0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Streams.FailableStream<IOException> streams_FailableStream0 = Functions.stream((Stream<IOException>) null);
      assertNotNull(streams_FailableStream0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Functions.FailableCallable<IOException, IOException> functions_FailableCallable0 = (Functions.FailableCallable<IOException, IOException>) mock(Functions.FailableCallable.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableCallable0).call();
      IOException iOException0 = Functions.call(functions_FailableCallable0);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Functions.FailableConsumer<IOException, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<IOException, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Consumer<IOException> consumer0 = Functions.asConsumer((Functions.FailableConsumer<IOException, ?>) functions_FailableConsumer0);
      assertNotNull(consumer0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      // Undeclared exception!
      try { 
        Functions.tryWithResources(functions_FailableRunnable0, functions_FailableRunnableArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // runnable
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Functions.FailableSupplier<IOException, IOException> functions_FailableSupplier0 = (Functions.FailableSupplier<IOException, IOException>) mock(Functions.FailableSupplier.class, new ViolatedAssumptionAnswer());
      Supplier<IOException> supplier0 = Functions.asSupplier((Functions.FailableSupplier<IOException, ?>) functions_FailableSupplier0);
      assertNotNull(supplier0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Functions functions0 = new Functions();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Functions.FailableBiConsumer<IntStream, IOException, IOException> functions_FailableBiConsumer0 = (Functions.FailableBiConsumer<IntStream, IOException, IOException>) mock(Functions.FailableBiConsumer.class, new ViolatedAssumptionAnswer());
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      MockIOException mockIOException0 = new MockIOException(mockRuntimeException0);
      Functions.accept(functions_FailableBiConsumer0, (IntStream) null, (IOException) mockIOException0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("");
      MockIOException mockIOException0 = new MockIOException("", mockRuntimeException0);
      Functions.FailableBiFunction<IOException, IOException, IOException, IOException> functions_FailableBiFunction0 = (Functions.FailableBiFunction<IOException, IOException, IOException, IOException>) mock(Functions.FailableBiFunction.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableBiFunction0).apply(any(java.io.IOException.class) , any(java.io.IOException.class));
      IOException iOException0 = Functions.apply(functions_FailableBiFunction0, (IOException) mockIOException0, (IOException) mockIOException0);
      assertSame(iOException0, mockIOException0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Functions.FailableCallable<IOException, IOException> functions_FailableCallable0 = (Functions.FailableCallable<IOException, IOException>) mock(Functions.FailableCallable.class, new ViolatedAssumptionAnswer());
      Callable<IOException> callable0 = Functions.asCallable((Functions.FailableCallable<IOException, ?>) functions_FailableCallable0);
      assertNotNull(callable0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("org.junitpioneer.jupiter.params.Range");
      // Undeclared exception!
      try { 
        Functions.test((Functions.FailableBiPredicate<IOException, IOException, IOException>) null, (IOException) mockIOException0, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      BiPredicate<IntStream, IntStream> biPredicate0 = Functions.asBiPredicate((Functions.FailableBiPredicate<IntStream, IntStream, ?>) null);
      assertNotNull(biPredicate0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      LinkedList<IOException> linkedList0 = new LinkedList<IOException>();
      Streams.FailableStream<IOException> streams_FailableStream0 = Functions.stream((Collection<IOException>) linkedList0);
      assertNotNull(streams_FailableStream0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      BiFunction<IntStream, IOException, Stream<IOException>> biFunction0 = Functions.asBiFunction((Functions.FailableBiFunction<IntStream, IOException, Stream<IOException>, ?>) null);
      assertNotNull(biFunction0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      BiConsumer<IOException, DoubleStream> biConsumer0 = Functions.asBiConsumer((Functions.FailableBiConsumer<IOException, DoubleStream, ?>) null);
      assertNotNull(biConsumer0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Runnable runnable0 = Functions.asRunnable(functions_FailableRunnable0);
      assertNotNull(runnable0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException("");
      MockIOException mockIOException0 = new MockIOException("", mockRuntimeException0);
      Functions.FailableConsumer<IOException, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<IOException, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.accept(functions_FailableConsumer0, (IOException) mockIOException0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Function<Stream<IOException>, IntStream> function0 = Functions.asFunction((Functions.FailableFunction<Stream<IOException>, IntStream, ?>) null);
      assertNotNull(function0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockIOException mockIOException0 = new MockIOException(" [rjU9\"'D5Z{9?", mockThrowable0);
      Functions.FailablePredicate<IOException, IOException> functions_FailablePredicate0 = (Functions.FailablePredicate<IOException, IOException>) mock(Functions.FailablePredicate.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(functions_FailablePredicate0).test(any(java.io.IOException.class));
      boolean boolean0 = Functions.test(functions_FailablePredicate0, (IOException) mockIOException0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MockIOException mockIOException0 = new MockIOException(" [rjU9\"'D5Z{9?", mockThrowable0);
      Functions.FailableFunction<IntStream, IOException, IOException> functions_FailableFunction0 = (Functions.FailableFunction<IntStream, IOException, IOException>) mock(Functions.FailableFunction.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableFunction0).apply(any(java.util.stream.IntStream.class));
      IOException iOException0 = Functions.apply(functions_FailableFunction0, (IntStream) null);
      assertSame(mockIOException0, iOException0);
  }
}
