/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 24 14:35:16 GMT 2025
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.lang.reflect.Array;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.concurrent.Callable;
import java.util.function.BiConsumer;
import java.util.function.BiFunction;
import java.util.function.BiPredicate;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;
import org.apache.commons.lang3.Functions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockIOException;
import org.evosuite.runtime.mock.java.lang.MockError;
import org.evosuite.runtime.mock.java.lang.MockRuntimeException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Functions_ESTest extends Functions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException> functions_FailableRunnable1 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableConsumer<Throwable, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<Throwable, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 9);
      functions_FailableRunnableArray0[0] = functions_FailableRunnable1;
      functions_FailableRunnableArray0[1] = functions_FailableRunnable1;
      functions_FailableRunnableArray0[2] = functions_FailableRunnable1;
      functions_FailableRunnableArray0[3] = functions_FailableRunnable1;
      functions_FailableRunnableArray0[4] = functions_FailableRunnable0;
      functions_FailableRunnableArray0[5] = functions_FailableRunnable1;
      functions_FailableRunnableArray0[6] = functions_FailableRunnable0;
      functions_FailableRunnableArray0[7] = functions_FailableRunnable1;
      functions_FailableRunnableArray0[8] = functions_FailableRunnable1;
      Functions.tryWithResources(functions_FailableRunnable1, functions_FailableConsumer0, functions_FailableRunnableArray0);
      assertEquals(9, functions_FailableRunnableArray0.length);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      MockIOException mockIOException1 = new MockIOException();
      Functions.FailableBiFunction<IOException, IOException, IOException, IOException> functions_FailableBiFunction0 = (Functions.FailableBiFunction<IOException, IOException, IOException, IOException>) mock(Functions.FailableBiFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableBiFunction0).apply(any(java.io.IOException.class) , any(java.io.IOException.class));
      IOException iOException0 = Functions.apply(functions_FailableBiFunction0, (IOException) mockIOException0, (IOException) mockIOException1);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException((String) null);
      MockIOException mockIOException1 = new MockIOException(mockIOException0);
      Functions.FailableBiConsumer<IOException, IOException, IOException> functions_FailableBiConsumer0 = (Functions.FailableBiConsumer<IOException, IOException, IOException>) mock(Functions.FailableBiConsumer.class, new ViolatedAssumptionAnswer());
      Functions.accept(functions_FailableBiConsumer0, (IOException) mockIOException1, (IOException) mockIOException0);
      assertFalse(mockIOException0.equals((Object)mockIOException1));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Functions.FailablePredicate<IOException, IOException> functions_FailablePredicate0 = (Functions.FailablePredicate<IOException, IOException>) mock(Functions.FailablePredicate.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(functions_FailablePredicate0).test(any(java.io.IOException.class));
      MockIOException mockIOException0 = new MockIOException((String) null);
      boolean boolean0 = Functions.test(functions_FailablePredicate0, (IOException) mockIOException0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Functions.FailablePredicate<IOException, IOException> functions_FailablePredicate0 = (Functions.FailablePredicate<IOException, IOException>) mock(Functions.FailablePredicate.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(functions_FailablePredicate0).test(any(java.io.IOException.class));
      MockIOException mockIOException0 = new MockIOException((String) null);
      boolean boolean0 = Functions.test(functions_FailablePredicate0, (IOException) mockIOException0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Functions.FailableBiPredicate<IOException, IOException, IOException> functions_FailableBiPredicate0 = (Functions.FailableBiPredicate<IOException, IOException, IOException>) mock(Functions.FailableBiPredicate.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(functions_FailableBiPredicate0).test(any(java.io.IOException.class) , any(java.io.IOException.class));
      MockError mockError0 = new MockError();
      MockIOException mockIOException0 = new MockIOException(mockError0);
      boolean boolean0 = Functions.test(functions_FailableBiPredicate0, (IOException) mockIOException0, (IOException) mockIOException0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Functions.FailableBiPredicate<IOException, IOException, IOException> functions_FailableBiPredicate0 = (Functions.FailableBiPredicate<IOException, IOException, IOException>) mock(Functions.FailableBiPredicate.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(functions_FailableBiPredicate0).test(any(java.io.IOException.class) , any(java.io.IOException.class));
      MockError mockError0 = new MockError();
      MockIOException mockIOException0 = new MockIOException(mockError0);
      boolean boolean0 = Functions.test(functions_FailableBiPredicate0, (IOException) mockIOException0, (IOException) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Functions.FailableSupplier<IOException, IOException> functions_FailableSupplier0 = (Functions.FailableSupplier<IOException, IOException>) mock(Functions.FailableSupplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableSupplier0).get();
      IOException iOException0 = Functions.get(functions_FailableSupplier0);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable((Throwable) null);
      MockIOException mockIOException0 = new MockIOException(mockThrowable0);
      Functions.FailableSupplier<IOException, IOException> functions_FailableSupplier0 = (Functions.FailableSupplier<IOException, IOException>) mock(Functions.FailableSupplier.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableSupplier0).get();
      IOException iOException0 = Functions.get(functions_FailableSupplier0);
      assertSame(mockIOException0, iOException0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Functions.FailableCallable<IOException, IOException> functions_FailableCallable0 = (Functions.FailableCallable<IOException, IOException>) mock(Functions.FailableCallable.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableCallable0).call();
      IOException iOException0 = Functions.call(functions_FailableCallable0);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      Functions.FailableCallable<IOException, IOException> functions_FailableCallable0 = (Functions.FailableCallable<IOException, IOException>) mock(Functions.FailableCallable.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableCallable0).call();
      IOException iOException0 = Functions.call(functions_FailableCallable0);
      assertSame(mockIOException0, iOException0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException((String) null);
      Functions.FailableFunction<IOException, IOException, IOException> functions_FailableFunction0 = (Functions.FailableFunction<IOException, IOException, IOException>) mock(Functions.FailableFunction.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(functions_FailableFunction0).apply(any(java.io.IOException.class));
      IOException iOException0 = Functions.apply(functions_FailableFunction0, (IOException) mockIOException0);
      assertNull(iOException0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable((Throwable) null);
      MockIOException mockIOException0 = new MockIOException(mockThrowable0);
      Functions.FailableFunction<IOException, IOException, IOException> functions_FailableFunction0 = (Functions.FailableFunction<IOException, IOException, IOException>) mock(Functions.FailableFunction.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableFunction0).apply(any(java.io.IOException.class));
      IOException iOException0 = Functions.apply(functions_FailableFunction0, (IOException) mockIOException0);
      assertSame(mockIOException0, iOException0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.run((Functions.FailableRunnable<IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      // Undeclared exception!
      try { 
        Functions.apply((Functions.FailableBiFunction<IOException, IOException, IOException, IOException>) null, (IOException) mockIOException0, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      // Undeclared exception!
      try { 
        Functions.accept((Functions.FailableConsumer<IOException, IOException>) null, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockRuntimeException mockRuntimeException0 = new MockRuntimeException();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockRuntimeException0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Functions.FailableConsumer<Throwable, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<Throwable, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.tryWithResources((Functions.FailableRunnable<? extends Throwable>) null, functions_FailableConsumer0, (Functions.FailableRunnable<? extends Throwable>[]) null);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      // Undeclared exception!
      try { 
        Functions.tryWithResources((Functions.FailableRunnable<? extends Throwable>) null, (Functions.FailableConsumer<Throwable, ? extends Throwable>) null, functions_FailableRunnableArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // A resource action must not be null.
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockThrowable0);
        fail("Expecting exception: UndeclaredThrowableException");
      
      } catch(UndeclaredThrowableException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      MockError mockError0 = new MockError();
      // Undeclared exception!
      try { 
        Functions.rethrow(mockError0);
        fail("Expecting exception: Error");
      
      } catch(Error e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("LnQ_Yaehby9O}~(");
      // Undeclared exception!
      try { 
        Functions.rethrow(mockIOException0);
        fail("Expecting exception: UncheckedIOException");
      
      } catch(UncheckedIOException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: LnQ_Yaehby9O}~(
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.rethrow((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // The Throwable must not be null.
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      functions_FailableRunnableArray0[0] = functions_FailableRunnable0;
      Functions.tryWithResources(functions_FailableRunnable0, functions_FailableRunnableArray0);
      assertEquals(1, functions_FailableRunnableArray0.length);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 2);
      // Undeclared exception!
      try { 
        Functions.tryWithResources(functions_FailableRunnableArray0[0], (Functions.FailableRunnable<? extends Throwable>[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Functions.FailablePredicate<IOException, IOException> functions_FailablePredicate0 = (Functions.FailablePredicate<IOException, IOException>) mock(Functions.FailablePredicate.class, new ViolatedAssumptionAnswer());
      Predicate<IOException> predicate0 = Functions.asPredicate((Functions.FailablePredicate<IOException, ?>) functions_FailablePredicate0);
      assertNotNull(predicate0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.call((Functions.FailableCallable<IOException, IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Consumer<IOException> consumer0 = Functions.asConsumer((Functions.FailableConsumer<IOException, ?>) null);
      assertNotNull(consumer0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Supplier<IOException> supplier0 = Functions.asSupplier((Functions.FailableSupplier<IOException, ?>) null);
      assertNotNull(supplier0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Functions functions0 = new Functions();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("B]bl5og");
      // Undeclared exception!
      try { 
        Functions.accept((Functions.FailableBiConsumer<IOException, IOException, IOException>) null, (IOException) mockIOException0, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("LnQ_Yaehby9O}~(");
      Functions.FailableBiFunction<IOException, IOException, IOException, IOException> functions_FailableBiFunction0 = (Functions.FailableBiFunction<IOException, IOException, IOException, IOException>) mock(Functions.FailableBiFunction.class, new ViolatedAssumptionAnswer());
      doReturn(mockIOException0).when(functions_FailableBiFunction0).apply(any(java.io.IOException.class) , any(java.io.IOException.class));
      IOException iOException0 = Functions.apply(functions_FailableBiFunction0, (IOException) null, (IOException) null);
      assertSame(mockIOException0, iOException0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Callable<IOException> callable0 = Functions.asCallable((Functions.FailableCallable<IOException, ?>) null);
      assertNotNull(callable0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.get((Functions.FailableSupplier<IOException, IOException>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      // Undeclared exception!
      try { 
        Functions.test((Functions.FailableBiPredicate<IOException, IOException, IOException>) null, (IOException) null, (IOException) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      BiPredicate<IOException, IOException> biPredicate0 = Functions.asBiPredicate((Functions.FailableBiPredicate<IOException, IOException, ?>) null);
      assertNotNull(biPredicate0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Functions.FailableBiFunction<IOException, IOException, IOException, IOException> functions_FailableBiFunction0 = (Functions.FailableBiFunction<IOException, IOException, IOException, IOException>) mock(Functions.FailableBiFunction.class, new ViolatedAssumptionAnswer());
      BiFunction<IOException, IOException, IOException> biFunction0 = Functions.asBiFunction((Functions.FailableBiFunction<IOException, IOException, IOException, ?>) functions_FailableBiFunction0);
      assertNotNull(biFunction0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Functions.FailableConsumer<IOException, IOException> functions_FailableConsumer0 = (Functions.FailableConsumer<IOException, IOException>) mock(Functions.FailableConsumer.class, new ViolatedAssumptionAnswer());
      Functions.accept(functions_FailableConsumer0, (IOException) null);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      BiConsumer<IOException, IOException> biConsumer0 = Functions.asBiConsumer((Functions.FailableBiConsumer<IOException, IOException, ?>) null);
      assertNotNull(biConsumer0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Functions.FailableRunnable<IOException>[] functions_FailableRunnableArray0 = (Functions.FailableRunnable<IOException>[]) Array.newInstance(Functions.FailableRunnable.class, 1);
      Runnable runnable0 = Functions.asRunnable(functions_FailableRunnableArray0[0]);
      assertNotNull(runnable0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Functions.FailableRunnable<IOException> functions_FailableRunnable0 = (Functions.FailableRunnable<IOException>) mock(Functions.FailableRunnable.class, new ViolatedAssumptionAnswer());
      Functions.run(functions_FailableRunnable0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Function<IOException, IOException> function0 = Functions.asFunction((Functions.FailableFunction<IOException, IOException, ?>) null);
      assertNotNull(function0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("", (Throwable) null);
      // Undeclared exception!
      try { 
        Functions.test((Functions.FailablePredicate<IOException, IOException>) null, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException("");
      // Undeclared exception!
      try { 
        Functions.apply((Functions.FailableFunction<IOException, IOException, IOException>) null, (IOException) mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.Functions", e);
      }
  }
}
